
[functions.lista-supermarkets-nearby]
enabled = true
verify_jwt = true
import_map = "./functions/lista-supermarkets-nearby/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/lista-supermarkets-nearby/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/lista-supermarkets-nearby/*.html" ]

[functions.universal-push-notify]
verify_jwt = false

[functions.garage-checkout]
enabled = true
verify_jwt = false
import_map = "./functions/garage-checkout/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/garage-checkout/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/garage-checkout/*.html" ]

[functions.asaas-webhook]
enabled = true
verify_jwt = false
import_map = "./functions/asaas-webhook/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/asaas-webhook/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/asaas-webhook/*.html" ]

[functions.finance-simulate-billing]
enabled = true
verify_jwt = false
import_map = "./functions/finance-simulate-billing/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/finance-simulate-billing/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/finance-simulate-billing/*.html" ]

[functions.finance-update-boleto]
enabled = true
verify_jwt = false
import_map = "./functions/finance-update-boleto/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/finance-update-boleto/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/finance-update-boleto/*.html" ]

[functions.whatsapp-chatbot]
enabled = true
verify_jwt = false
import_map = "./functions/import_map.json"
entrypoint = "./functions/whatsapp-chatbot/index.ts"

[functions.whatsapp-dashboard]
enabled = true
verify_jwt = false
entrypoint = "./functions/whatsapp-dashboard/index.ts"

