import 'package:powersync/powersync.dart';

const psSchema = Schema([
  Table('condominios', [
    Column.text('nome'),
    Column.text('apelido'),
    Column.text('cnpj'),
    Column.text('cep'),
    Column.text('logradouro'),
    Column.text('bairro'),
    Column.text('numero'),
    Column.text('complemento'),
    Column.text('cidade'),
    Column.text('estado'),
    Column.text('created_at'),
  ]),
  Table('blocos', [
    Column.text('condominio_id'),
    Column.text('nome_ou_numero'),
    Column.text('created_at'),
  ]),
  Table('apartamentos', [
    Column.text('condominio_id'),
    Column.text('numero'),
    Column.text('created_at'),
  ]),
  Table('unidades', [
    Column.text('condominio_id'),
    Column.text('bloco_id'),
    Column.text('apartamento_id'),
    Column.integer('bloqueada'),
    Column.text('created_at'),
  ]),
  Table('perfil', [
    Column.text('condominio_id'),
    Column.text('nome_completo'),
    Column.text('email'),
    Column.text('whatsapp'),
    Column.integer('whatsapp_msg_consent'),
    Column.integer('bloqueado'),
    Column.text('status_aprovacao'),
    Column.text('tipo_morador'),
    Column.text('papel_sistema'),
    Column.text('bloco_txt'),
    Column.text('apto_txt'),
    Column.text('historico_status'),
    Column.text('fcm_token'),
    Column.text('botconversa_id'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('unidade_perfil', [
    Column.text('perfil_id'),
    Column.text('unidade_id'),
    Column.text('created_at'),
  ]),
  Table('encomendas', [
    Column.text('resident_id'),
    Column.text('condominio_id'),
    Column.text('status'),
    Column.text('arrival_time'),
    Column.text('delivery_time'),
    Column.text('photo_url'),
    Column.text('pickup_proof_url'),
    Column.text('created_at'),
  ]),
  Table('convites', [
    Column.text('resident_id'),
    Column.text('condominio_id'),
    Column.text('guest_name'),
    Column.text('validity_date'),
    Column.text('qr_data'),
    Column.text('status'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('sos_alertas', [
    Column.text('resident_id'),
    Column.text('condominium_id'), // A migração usa condominium_id (English) nesta tabela específica
    Column.real('latitude'),
    Column.real('longitude'),
    Column.text('status'),
    Column.text('acknowledged_by'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('ocorrencias', [
    Column.text('resident_id'),
    Column.text('condominium_id'), // A migração usa condominium_id (English) nesta tabela específica
    Column.text('description'),
    Column.text('category'),
    Column.text('status'),
    Column.text('photo_paths'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('reservas_areas', [
    Column.text('condominio_id'),
    Column.text('area_id'),
    Column.text('resident_id'),
    Column.text('booking_date'),
    Column.text('status'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('areas_comuns', [
    Column.text('condominio_id'),
    Column.text('nome'),
    Column.text('descricao'),
    Column.text('regras'),
    Column.text('foto_url'),
    Column.text('created_at'),
  ]),
  Table('mensagens_chat', [
    Column.text('resident_id'),
    Column.text('condominio_id'),
    Column.text('sender_id'),
    Column.text('sender_role'),
    Column.text('text'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('documentos', [
    Column.text('condominio_id'),
    Column.text('title'),
    Column.text('category'),
    Column.text('file_url'),
    Column.text('file_extension'),
    Column.text('upload_date'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('assembleias', [
    Column.text('condominio_id'),
    Column.text('titulo'),
    Column.text('descricao'),
    Column.text('data_inicio'),
    Column.text('data_fim'),
    Column.text('status'),
    Column.text('created_at'),
  ]),
  Table('opcoes_assembleia', [
    Column.text('assembleia_id'),
    Column.text('titulo'),
    Column.text('created_at'),
  ]),
  Table('votos_assembleia', [
    Column.text('assembleia_id'),
    Column.text('opcao_id'),
    Column.text('perfil_id'),
    Column.text('created_at'),
  ]),
  Table('itens_inventario', [
    Column.text('condominio_id'),
    Column.text('nome'), // Alinhado: 'nome' (Portuguese)
    Column.text('descricao'),
    Column.text('categoria'),
    Column.integer('quantidade_atual'),
    Column.integer('quantidade_minima'),
    Column.integer('eh_consumivel'),
    Column.text('created_at'),
    Column.text('updated_at'),
  ]),
  Table('transacoes_inventario', [
    Column.text('item_id'),
    Column.text('perfil_id'),
    Column.text('tipo_transacao'),
    Column.integer('quantidade'),
    Column.text('notas'),
    Column.text('created_at'),
  ]),
  Table('user_consents', [
    Column.text('user_id'),
    Column.text('consent_type'),
    Column.text('granted_at'),
    Column.text('revoked_at'),
    Column.text('created_at'),
  ]),
]);
