// File generated by Antigravity - manual configuration
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe2YbC2kOcxQAhs0IYtzT-h8ZOuybEKVM',
    appId: '1:239069018659:android:2bfa045c2823e9d4fccf96',
    messagingSenderId: '239069018659',
    projectId: 'condomeet-oficial',
    storageBucket: 'condomeet-oficial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDMEl2wCA4uDg-vZ2kJPgEKD80OuuxIqY',
    appId: '1:239069018659:ios:8d6b005c96d2d966fccf96',
    messagingSenderId: '239069018659',
    projectId: 'condomeet-oficial',
    storageBucket: 'condomeet-oficial.firebasestorage.app',
    iosBundleId: 'br.app.condomeet.home',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDMEl2wCA4uDg-vZ2kJPgEKD80OuuxIqY',
    appId: '1:239069018659:ios:8d6b005c96d2d966fccf96',
    messagingSenderId: '239069018659',
    projectId: 'condomeet-oficial',
    storageBucket: 'condomeet-oficial.firebasestorage.app',
    iosBundleId: 'br.app.condomeet.home',
  );
}
