-- Migration: Import 'Fale Conosco' threads and messages from old system
-- Threads: 17, Messages: 40
-- Generated by generate_fale_sindico_import.py

DO $$
DECLARE
  v_condo_montserrat UUID := '4828f5f6-454c-438c-9ef3-9f1bf5a7ab94';
  v_condo_recanto    UUID := 'b699e35f-c2f9-461f-93c3-de8a80e73744';
  v_user_id UUID;
  v_sender_id UUID;
  v_condo_id UUID;
  v_thread_id UUID;
  v_count_threads INT := 0;
  v_count_msgs INT := 0;
  v_skipped INT := 0;
  rec RECORD;
  msg RECORD;
BEGIN

  -- 1. Temp table for threads
  CREATE TEMP TABLE tmp_fale_threads (
    old_id INT, old_condo_id INT, created_at TIMESTAMPTZ,
    bloco TEXT, apto TEXT, assunto TEXT,
    tipo TEXT, status TEXT
  );

  INSERT INTO tmp_fale_threads VALUES
  (12,42,'2025-08-30 13:29:44.067248-03','125','303','Outros...','sugestao','respondido'),
  (13,42,'2025-09-02 09:50:15.641923-03','87','301','Reclamação','reclamacao','respondido'),
  (14,42,'2025-09-03 12:39:43.278177-03','87','301','Reclamação','reclamacao','respondido'),
  (15,42,'2025-09-03 12:42:12.566893-03','87','301','Reclamação','reclamacao','respondido'),
  (16,42,'2025-09-03 21:48:08.768747-03','87','301','Elogio','elogio','respondido'),
  (18,42,'2025-09-07 12:01:18.869668-03','86','103','Reclamação','reclamacao','respondido'),
  (19,42,'2025-10-05 11:12:05.736073-03','56','204','Reclamação','reclamacao','respondido'),
  (20,42,'2025-10-10 14:37:48.346732-03','85','202','Outros...','sugestao','respondido'),
  (21,42,'2025-10-28 12:00:02.45888-03','125','303','Outros...','sugestao','respondido'),
  (22,42,'2025-11-25 09:52:47.260182-03','125','301','Mensagem','sugestao','respondido'),
  (23,42,'2025-12-06 13:46:34.881504-03','71','201','Outros...','sugestao','respondido'),
  (24,42,'2025-12-19 13:32:46.061701-03','125','301','Mensagem','sugestao','respondido'),
  (25,42,'2025-12-25 19:33:52.365518-03','125','301','Mensagem','sugestao','respondido'),
  (26,42,'2025-12-28 16:38:11.233454-03','32','103','Mensagem','sugestao','respondido'),
  (27,41,'2026-02-04 19:13:08.793142-03','A','503','Outros...','sugestao','respondido'),
  (28,42,'2026-02-08 20:32:19.767203-03','86','103','Outros...','sugestao','respondido'),
  (29,42,'2026-03-15 11:15:33.388364-03','124','301','Dúvida','duvida','respondido');

  -- 2. Temp table for messages
  CREATE TEMP TABLE tmp_fale_msgs (
    old_id INT, thread_old_id INT, created_at TIMESTAMPTZ,
    bloco TEXT, apto TEXT, is_admin BOOLEAN,
    texto TEXT, sender_name TEXT
  );

  INSERT INTO tmp_fale_msgs VALUES
  (35,12,'2025-08-30 13:29:44.275982-03','125','303',false,'PRECISO DE UM ELETRICISTA PARA FAZER MANUTENÇÃO DO CHUVEIRO ELÉTRICO!','Nalbert'),
  (36,13,'2025-09-02 09:50:15.798769-03','87','301',false,'Bom dia.
Venho, por meio desta, solicitar formalmente a limpeza dos fundos do bloco 87. Ressalto que já havia encaminhado vídeo no dia 28/08 e, novamente, no dia 02/09, ambos informados pelo WhatsApp da secretaria do condomínio, no número +55 22 99227-5387.

Sugestão: a mesma pessoa responsável pela limpeza da frente também deverá se encarregar da limpeza dos fundos.

Acabou de acontecer enquanto eu escrevia. Vide o último vídeo, no qual o funcionário observa a placa de vidro e nada faz.

Agradeço desde já pela atenção e aguardo providências.','Moacyr'),
  (37,12,'2025-09-02 17:19:43.219538-03','16','101',true,'Boa tarde! Érico 998459860 (ele é eletricista e é o zelador do condomínio). Att, Francielle Baptista.','Administração'),
  (38,14,'2025-09-03 12:39:43.504272-03','87','301',false,'Boa tarde, a falta da limpeza atrás do bloco 87 permanece, vide o vídeo enviado para o WhatsApp do condomínio.

Copio a mensagem anterior: 

Bom dia.
Venho, por meio desta, solicitar formalmente a limpeza dos fundos do bloco 87. Ressalto que já havia encaminhado vídeo no dia 28/08 e, novamente, no dia 02/09, ambos informados pelo WhatsApp da secretaria do condomínio, no número +55 22 99227-5387.

Sugestão: a mesma pessoa responsável pela limpeza da frente também deverá se encarregar da limpeza dos fundos.

Acabou de acontecer enquanto eu escrevia. Vide o último vídeo, no qual o funcionário observa a placa de vidro e nada faz.

Agradeço desde já pela atenção e aguardo providências.
Criado no dia: 02/09/2025, 9:50 am','Moacyr'),
  (39,15,'2025-09-03 12:42:12.724968-03','87','301',false,'Boa tarde, venho acusar a falta da limpeza atrás do bloco 87, conforme já enviado hoje (03/09) no WhatsApp do condomínio.

Remeto a mensagem anterior:


Bom dia.
Venho, por meio desta, solicitar formalmente a limpeza dos fundos do bloco 87. Ressalto que já havia encaminhado vídeo no dia 28/08 e, novamente, no dia 02/09, ambos informados pelo WhatsApp da secretaria do condomínio, no número +55 22 99227-5387.

Sugestão: a mesma pessoa responsável pela limpeza da frente também deverá se encarregar da limpeza dos fundos.

Acabou de acontecer enquanto eu escrevia. Vide o último vídeo, no qual o funcionário observa a placa de vidro e nada faz.

Agradeço desde já pela atenção e aguardo providências.
Criado no dia: 02/09/2025, 9:50 am','Moacyr'),
  (40,15,'2025-09-03 14:20:08.074524-03','16','101',true,'Boa tarde! Mais uma vez solicitei a limpeza novamente, ontem foi feita, mas o encarregado irá verificar novamente. Att, Francielle Baptista.','Administração'),
  (41,14,'2025-09-03 14:20:13.875794-03','16','101',true,'Boa tarde! Mais uma vez solicitei a limpeza novamente, ontem foi feita, mas o encarregado irá verificar novamente. Att, Francielle Baptista.','Administração'),
  (42,13,'2025-09-03 14:21:22.052464-03','16','101',true,'Boa tarde! Mais uma vez solicitei a limpeza novamente, ontem foi feita, mas o encarregado irá verificar novamente. Nós temos outro contato na administração também, que é o 22 992163473. Att, Francielle Baptista.','Administração'),
  (45,15,'2025-09-03 17:46:37.427109-03','87','301',false,'Boa tarde.
O vídeo que enviei hoje foi gravado na própria data. É possível que, em ocasiões anteriores, algumas informações não tenham sido transmitidas corretamente. Contudo, não há qualquer razão para que se levantem inverdades em uma queixa condominial, não é mesmo?

Peço que verifique com atenção, pois amanhã realizarei nova inspeção. Caso encontre novamente a mesma situação de descuido e podridão, não me restará alternativa senão ajuizar uma ação judicial para pagar o condomínio. 

Ressalto que o pagamento será efetuado apenas no próximo mês, até porque venho quitando as cotas condominiais de forma antecipada, sempre no mês anterior ao vencimento.

Repito, sei da sua boa vontade, mas, não pegue informações dada por terceiros antes de checar. 

Agradeço a atenção.','Moacyr'),
  (46,13,'2025-09-03 17:47:12.532215-03','87','301',false,'Boa tarde.
O vídeo que enviei hoje foi gravado na própria data. É possível que, em ocasiões anteriores, algumas informações não tenham sido transmitidas corretamente. Contudo, não há qualquer razão para que se levantem inverdades em uma queixa condominial, não é mesmo?

Peço que verifique com atenção, pois amanhã realizarei nova inspeção. Caso encontre novamente a mesma situação de descuido e podridão, não me restará alternativa senão ajuizar uma ação judicial para pagar o condomínio. 

Ressalto que o pagamento será efetuado apenas no próximo mês, até porque venho quitando as cotas condominiais de forma antecipada, sempre no mês anterior ao vencimento.

Repito, sei da sua boa vontade, mas, não pegue informações dada por terceiros antes de checar. 

Agradeço a atenção.','Moacyr'),
  (47,14,'2025-09-03 17:48:09.713747-03','87','301',false,'Boa tarde.
O vídeo que enviei hoje foi gravado na própria data. É possível que, em ocasiões anteriores, algumas informações não tenham sido transmitidas corretamente. Contudo, não há qualquer razão para que se levantem inverdades em uma queixa condominial, não é mesmo?

Peço que verifique com atenção, pois amanhã realizarei nova inspeção. Caso encontre novamente a mesma situação de descuido e podridão, não me restará alternativa senão ajuizar uma ação judicial para pagar o condomínio. 

Ressalto que o pagamento será efetuado apenas no próximo mês, até porque venho quitando as cotas condominiais de forma antecipada, sempre no mês anterior ao vencimento.

Repito, sei da sua boa vontade, mas, não pegue informações dada por terceiros antes de checar. 

Agradeço a atenção.','Moacyr'),
  (48,16,'2025-09-03 21:48:08.92716-03','87','301',false,'Boa noite,

Venho agradecer pelo serviço realizado hoje, conforme o vídeo encaminhado ao WhatsApp do condomínio (+55 22 99227-5387), gravado na noite de 03/09, às 21h28min.

Ressalto que este pedido já havia sido solicitado desde quinta-feira passada, dia 28/08.

Espero que a limpeza seja mantida regularmente, em conformidade com o regulamento interno.

Agradeço pela atenção.','Moacyr'),
  (49,16,'2025-09-04 09:25:52.068892-03','16','101',true,'Bom dia, Moacyr. Agradeço o retorno, solicitarei uma revisão, mas fico a disposição para resolver essas questões. Att, Francielle Baptista.','Administração'),
  (51,18,'2025-09-07 12:01:19.269048-03','86','103',false,'MANUTENÇÃO 

NO BL 86 NO ROL DE ENTRADA PARTE EXTÉRNA
LÂMPADA SE ENCONTRA QUEIMADA 

DESDE JÁ AGRADEÇO 
L','Narla Jane Boldes de Castro'),
  (52,18,'2025-09-08 09:30:48.880935-03','16','101',true,'Bom dia, vou solicitar a troca. Att, Francielle Baptista.','Administração'),
  (53,19,'2025-10-05 11:12:06.161668-03','56','204',false,'Estou tentando falar desde cedo com a síndica responsável de hoje e não estou conseguindo. Preciso da liberação para saída de uma cama do meu apartamento e não estou conseguindo resolver isso. Moro a pouco tempo aqui, e não sabia que precisava de autorização para tal coisa. Ninguém nunca me informou sobre,eu nunca morei em condomínio. Peço que me ajude a resolver isso. O rapaz já está aqui para levar uma cama.. grata','Maria Antonia'),
  (54,20,'2025-10-10 14:37:48.544377-03','85','202',false,'Boa tarde 
Sou proprietário do apartamento 202, BL 85. Eu sempre aluguei, mas resolvi não alugar mais. Por isso, só agora percebi. O chão da minha cozinha está com várias rachaduras grandes e o piso está com ondas e oco. No quarto menor tem uma outra rachadura no teto. Tem como verificar se elas ocorrem nos apartamentos tanto debaixo como de cima. É algo que merece uma investigação, pois se trata de rachaduras que podem comprometer a estrutura.','Rodrigo Rodrigues'),
  (55,20,'2025-10-10 14:47:31.368098-03','16','101',true,'Boa tarde! Eu posso marcar um horário para que um dos nossos funcionários verifique as rachaduras no seu apartamento. Qual seria a sua disponibilidade? Att, Francielle Baptista.','Administração'),
  (56,20,'2025-10-10 14:56:52.284572-03','85','202',false,'Eu estou em São Francisco e talvez amanhã. Posso confirmar com.vc só amanhã .','Rodrigo Rodrigues'),
  (61,21,'2025-10-28 12:00:02.705859-03','125','303',false,'PROCURANDO UM APARTAMENTO MOBILIANDO DENTRO DO CONDOMÍNIO RECANTO DAS PALMEIRAS','Nalbert'),
  (62,21,'2025-10-30 14:46:14.94042-03',NULL,NULL,true,'Boa tarde! Precisa vim na administração para olhar o livro de vendas e aluguel. Att, Francielle Baptista.',NULL),
  (63,22,'2025-11-25 09:52:47.408254-03','125','301',false,'Sábado pode ser feito alguma obra no condomínio?','Emanoel'),
  (64,22,'2025-11-25 10:00:39.090187-03','16','101',true,'Bom dia! Sábado pode de 8 às 12h. Att, Francielle Baptista.','administração'),
  (65,23,'2025-12-06 13:46:35.174336-03','71','201',false,'Boa tarde. 
Desmontei um pequeno guarda roupa agora aqui no meu apto. 
Doei para uma pessoa carente. 
Gostaria de autorização para acesso retirada','Carlos Barroso'),
  (66,24,'2025-12-19 13:32:46.198365-03','125','301',false,'Marquei um jogo ontem à noite noite no campinho lá atrás e não tinha luz para poder jogar, queria saber se teria como ajeitar a iluminação para poder jogar bola','Emanoel'),
  (67,24,'2025-12-19 14:05:57.165583-03','125','301',false,'Fui jogar uma bola no campo do condomínio e a iluminação estava muito ruim, queria saber se teria como colocar outros refletores tbm','Emanoel'),
  (68,24,'2025-12-19 14:32:41.399823-03','16','101',true,'Boa tarde! Acredito que não seja feito agora. Mas vou passar para o síndico de plantão. Att, Francielle Baptista.','administração'),
  (69,25,'2025-12-25 19:33:52.50333-03','125','301',false,'Boa noite, queria fazer uma reserva','Emanoel'),
  (70,25,'2025-12-26 09:29:54.957475-03','16','101',true,'Bom dia! Reservas são feitas apenas na administração. Mediante assinatura de contrato. Att, Francielle Baptista.','administração'),
  (71,26,'2025-12-28 16:38:11.677149-03','32','103',false,'Olá meu nome é Eleni e miro no bloco 32 apto 103. E trabalho como cuidadora. Não tem como liberar a piscina por favor ? Eu já fiz exames de saúde. Não tenho doenças contagiosas. E atestado só pagando particular.','Eleni Soares'),
  (72,26,'2025-12-29 09:34:16.179798-03','16','101',true,'Bom dia! Para usar a piscina precisa do atestado dizendo que você está apta a usar a piscina. Essa norma está na nossa convenção.','Administração'),
  (73,19,'2026-01-31 16:33:17.781243-03','56','204',false,'Boa tarde! Estou sem energia, gostaria de saber se está acontecendo isso em outros apartamentos? E se VCS sabem o que está acontecendo? Grata.','Maria Antonia'),
  (74,27,'2026-02-04 19:13:09.057063-03','A','503',false,'Olá boa noite

Inclui uma reserva para realização de mudança nesta sexta-feira dia 06/02, gostaria de confirmar se está tudo ok.

Obrigada','Izabelle'),
  (75,27,'2026-02-06 20:40:20.031732-03','A','206',true,'Desculpe, esta semana foi tanta coisa que não vi o app. Mas e a mudança deu tudo certo?','Adriana Ricardo Leonarde'),
  (76,27,'2026-02-07 21:24:24.708439-03','A','503',false,'Deu tudo certo.

Obrigada','Izabelle'),
  (77,28,'2026-02-08 20:32:20.393133-03','86','103',false,'Bom dia!

A lâmpada da parte EXTERÑA fo rol 

de entrada se encontra queimada 




       Grata','Narla Jane Boldes de Castro'),
  (79,26,'2026-03-13 12:56:26.899479-03','32','103',false,'Certo. Mas encontrei um senhorzinho la que falou com o síndico e foi autorizado. Se pode pra uma teria que poder pra todos.','Eleni Soares'),
  (80,29,'2026-03-15 11:15:33.679321-03','124','301',false,'Bom dia não consigo autorizar entrada de visitantes pelo meu aplicativo só o meu esposo','Renalígia'),
  (81,29,'2026-03-16 14:26:10.279938-03',NULL,NULL,true,'Boa tarde! Pode vim aqui na administração, para eu tentar te ajudar. Att, Francielle Baptista.',NULL),
  (82,26,'2026-03-16 14:27:08.152698-03',NULL,NULL,true,'Boa tarde! A norma é liberar apenas com atestado.',NULL);

  -- 3. Map old thread IDs to new UUIDs
  CREATE TEMP TABLE tmp_thread_map (
    old_id INT, new_id UUID
  );

  -- 4. Insert threads
  FOR rec IN SELECT * FROM tmp_fale_threads ORDER BY old_id LOOP
    CASE rec.old_condo_id
      WHEN 41 THEN v_condo_id := v_condo_montserrat;
      WHEN 42 THEN v_condo_id := v_condo_recanto;
      ELSE v_condo_id := NULL;
    END CASE;

    IF v_condo_id IS NULL THEN v_skipped := v_skipped + 1; CONTINUE; END IF;

    SELECT id INTO v_user_id FROM public.perfil
      WHERE condominio_id = v_condo_id
        AND UPPER(TRIM(bloco_txt)) = UPPER(TRIM(rec.bloco))
        AND TRIM(apto_txt) = TRIM(rec.apto)
      ORDER BY created_at DESC LIMIT 1;

    IF v_user_id IS NULL THEN
      v_skipped := v_skipped + 1;
      RAISE NOTICE 'SKIP thread old_id=% bloco=% apto=%', rec.old_id, rec.bloco, rec.apto;
      CONTINUE;
    END IF;

    INSERT INTO public.fale_sindico_threads (
      condominio_id, resident_id, tipo, assunto, status,
      ultima_mensagem_em, created_at
    ) VALUES (
      v_condo_id, v_user_id, rec.tipo, rec.assunto, rec.status,
      rec.created_at, rec.created_at
    ) RETURNING id INTO v_thread_id;

    INSERT INTO tmp_thread_map VALUES (rec.old_id, v_thread_id);
    v_count_threads := v_count_threads + 1;
  END LOOP;

  -- 5. Insert messages
  FOR msg IN SELECT m.*, tm.new_id AS new_thread_id
             FROM tmp_fale_msgs m
             JOIN tmp_thread_map tm ON tm.old_id = m.thread_old_id
             ORDER BY m.old_id
  LOOP
    -- Find sender
    IF msg.is_admin THEN
      -- Admin message: find admin by name or use first admin of that condo
      SELECT t.resident_id INTO v_sender_id
        FROM public.fale_sindico_threads t
        WHERE t.id = msg.new_thread_id;
      -- Try to find actual admin sender
      IF msg.bloco IS NOT NULL AND msg.bloco <> '' AND msg.apto IS NOT NULL AND msg.apto <> '' THEN
        SELECT p.id INTO v_sender_id FROM public.perfil p
          WHERE p.condominio_id = (SELECT condominio_id FROM public.fale_sindico_threads WHERE id = msg.new_thread_id)
            AND UPPER(TRIM(p.bloco_txt)) = UPPER(TRIM(msg.bloco))
            AND TRIM(p.apto_txt) = TRIM(msg.apto)
            AND p.papel_sistema IN ('ADMIN', 'Síndico')
          ORDER BY p.created_at DESC LIMIT 1;
      END IF;
      -- Fallback: use thread resident as sender (at least it won't be NULL)
      IF v_sender_id IS NULL THEN
        SELECT t.resident_id INTO v_sender_id
          FROM public.fale_sindico_threads t
          WHERE t.id = msg.new_thread_id;
      END IF;
    ELSE
      -- Resident message: use thread's resident_id
      SELECT t.resident_id INTO v_sender_id
        FROM public.fale_sindico_threads t
        WHERE t.id = msg.new_thread_id;
    END IF;

    INSERT INTO public.fale_sindico_mensagens (
      thread_id, sender_id, is_admin, texto, created_at
    ) VALUES (
      msg.new_thread_id, v_sender_id, msg.is_admin, msg.texto, msg.created_at
    );
    v_count_msgs := v_count_msgs + 1;

    -- Update thread's ultima_mensagem_em
    UPDATE public.fale_sindico_threads
      SET ultima_mensagem_em = msg.created_at
      WHERE id = msg.new_thread_id
        AND ultima_mensagem_em < msg.created_at;
  END LOOP;

  DROP TABLE tmp_fale_threads;
  DROP TABLE tmp_fale_msgs;
  DROP TABLE tmp_thread_map;

  RAISE NOTICE '=== FALE SINDICO IMPORT: % threads, % messages, % skipped ===', v_count_threads, v_count_msgs, v_skipped;
END $$;
