-- Migration: Import occurrences from old system
-- Recanto das Palmeiras (condominio_id=42)
-- Total records to process: 24
-- Generated by generate_ocorrencias_import.py
-- IMPORTANT: Triggers are disabled during import

DO $$
DECLARE
  v_condo_montserrat UUID := '4828f5f6-454c-438c-9ef3-9f1bf5a7ab94';
  v_condo_recanto    UUID := 'b699e35f-c2f9-461f-93c3-de8a80e73744';
  v_user_id UUID;
  v_condo_id UUID;
  v_count INT := 0;
  v_skipped INT := 0;
  rec RECORD;
BEGIN


  -- 1. Create temp table with old data
  CREATE TEMP TABLE tmp_ocorrencias_import (
    old_id INT,
    old_condo_id INT,
    created_at TIMESTAMPTZ,
    apto TEXT,
    bloco TEXT,
    assunto TEXT,
    description TEXT,
    status TEXT,
    admin_response TEXT,
    admin_response_at TIMESTAMPTZ
  );

  INSERT INTO tmp_ocorrencias_import VALUES
  (16,42,'2025-04-05 12:58:59.031356-03','103','86','MANUTENÇÃO','VENHO POR MEIO DESTA SOLICITAR A TROCA DA FECHADURA DA PORTA DO ROL DE ENTRADA DO BLOCO 86.

DESDE JA AGRADEÇO Á ATENÇÃO!!','resolved','Boa tarde! Ela estás sendo consertada nesse momento. Att, Francielle Baptista.','2025-04-08 15:08:59.554-03'),
  (17,42,'2025-04-08 23:43:38.247258-03','103','86','MANUTENÇÃO','Venho por meio desta maisuma vez,solicitar a TROCA DA FECHADURA do bloco:86,do rol de entrada! 
A resposta dada a OCORRÊNCIA N°1, NÃO condiz com o ocorrido! A FECHADURA NÃO foi trocada,nem mexida!Está do mesmo jeito!!','resolved','Bom dia! O funcionário vai passar no seu apartamento, só não posso te confirmar o horário. Caso o problema persista pode entrar em contato novamente. Att, Francielle Baptista.','2025-04-09 10:22:21.893-03'),
  (19,42,'2025-04-19 22:56:07.427399-03','104','39','Barulho excessivo','Meu vizinho de cima, apartamento 204, desde que chegou simplesmente vivem como se não tivessem vizinho embaixo, chegou ao ápice nesse feriado que ele está recebendo visita em casa, com muito barulho, crianças pulando, porque não anda, o tempo todo com um barulho em cima de nossa cabeça que é irritante, várias vezes somos acordados com o barulho da criança correndo ou fazendo bagunça isso antes das 7 da manhã e pra dormir sempre após as 22 como agora as 22:52 estou com sono, irritado por não conseguir dormir por conta do barulho em cima da nossa cabeça, entendo que é criança mas eles não entendem que vivem em comunidade e tem limites, não quero e nem peço que a criança pare de brincar e sei que é difícil controlar, mas não há empatia e eles também não tomam nenhuma providência, não quero ser o vizinho chato, mas está atrapalhando meu sono, descanso, ultimamente passo mais tempo fora do que na minha casa pra não me irritar, só estou fazendo esta ocorrência pq não sei mais oque fazer, está insuportável, de verdade, preciso que seja feito algo, não aguentamos mais.
Eles moram no bloco 39 apartamento 204.','resolved','Bom dia! A situação já foi passada para o síndico, e ele entrou em contato com os moradores. Caso os barulhos persistam, peço que entre em contato conosco novamente.
Att, Francielle Baptista.','2025-04-22 16:24:41.134-03'),
  (20,42,'2025-04-24 23:56:12.64465-03','101','49','Vazamento e incomodo','Boa noite, o morador de cima do meu AP , todos os dias fica arrastando móveis, farreando tarda da noite, e criança que fica pulando lá em cima , como não bastace o vazamento que está vindo do apartamento deles na minha cozinha que está estragado meu móvel...','resolved','Boa tarde! Sua situação foi passada na sexta feira, ela entrar em contato com os moradores, pois no cadastro não tem nenhuma criança registrada, apenas a bebê deles que tem poucos meses. Com relação a infiltração vou te passar o contato deles para vocês conversarem, Vinicius 998718099 ou Camila 998614654. Att, Francielle Baptista.','2025-04-28 17:47:33.597-03'),
  (21,42,'2025-05-14 10:09:18.506127-03','301','116','Fios soltos','Bom dia ! Tudo bem ?
- Na lateral do app tem uns fios soltos, que em qualquer vento, eles fazem barulho. 
 E neste tempo mais frio, faz esse barulho constantemente. Não há como dormir no quarto, pois o barulho é muito alto.
Já comuniquei 2 vezes a administração!!!
  As vezes, se prender os fios seja resolve.','resolved','Boa tarde! Pedi que o encarregado verifique quais os tipos de fios, ele vai verificar e orientar o que deve ser feito. Att, Francielle Baptista.','2025-05-14 14:16:34.539-03'),
  (28,42,'2025-08-16 09:04:54.458988-03','202','48','Provável cachorro perdido','Cachorro da raça Shitzu avistado próximo ao bloco 44, branco com manchas marrom escuro e pretas, visto as 9h, do dia 16/08. Indo em direção ao bloco 45','resolved','Boa tarde! No sábado não recebemos nenhuma informação, mas vamos ficar atentos. Talvez o dono tenha encontrado, mas vamos ficar atentos. Obrigada por avisar. Atenciosamente, Francielle Baptista.','2025-08-18 16:50:58.212-03'),
  (29,42,'2025-08-19 19:49:19.531204-03','303','16','Falta de limpeza no meu bloco. Bloco 16.','Ha dois dias o bloco não e limpo, tem vestígios de água de lixo, um pedaço de papel higiênico sujo de fezes, é o que parece, estamos sem trabalhadores? Férias? Bloco 16.','resolved','Boa tarde! Iremos verificar e já solicitar a limpeza. Atenciosamente, Francielle Baptista.','2025-08-20 15:43:17.586-03'),
  (30,42,'2025-09-02 08:51:07.394514-03','301','87','Reclamação','Bom dia.
Venho, por meio desta, solicitar formalmente a limpeza dos fundos do bloco 87. Ressalto que já havia encaminhado vídeo no dia 28/08 e, novamente, no dia 02/09, ambos informados pelo WhatsApp da secretaria do condomínio, no número +55 22 99227-5387.

Sugestão: a mesma pessoa responsável pela limpeza da frente também deverá se encarregar da limpeza dos fundos.

Acabou de acontecer enquanto eu escrevia. Vide o último vídeo, no qual o funcionário observa a placa de vidro e nada faz.

Agradeço desde já pela atenção e aguardo providências.','resolved','Bom dia, Moacyr. Irei solicitar a limpeza novamente. Att, Francielle Baptista.','2025-09-02 10:22:41.107-03'),
  (31,42,'2025-09-03 12:43:43.056214-03','301','87','Reclamação','Boa tarde, vendo acusar a ausência da limpeza atrás do bloco 87, conforme já encaminhado por WhatsApp do condomínio hoje.','pending',NULL,NULL),
  (32,42,'2025-09-07 11:53:02.817106-03','103','86','Manutenção','Solicito a troca
No bloco 86 no rol de entrada na parte EXTERNA lâmpada se encontra queimada!
Desde já agradeço!','pending',NULL,NULL),
  (33,42,'2025-09-07 11:57:42.338571-03','103','86','Manutenção','Solicito a troca

No bl 86 no rol de entrada parte EXTERNA lâmpada queimada

Desde já agradeço!','resolved','Bom dia! Será trocada! Att, Francielle Baptista.','2025-09-08 09:32:52.855-03'),
  (34,42,'2025-10-05 11:24:21.980562-03','204','56','Retirada de uma cama do meu apartamento.','Bom dia! Estou tentando falar com o síndico de plantão e não estou conseguindo falar. Eu trabalho de segunda a sábado,não tenho tempo para fazer mudança. Não sabia que para tirar qualquer coisa do meu apartamento,teria que ter autorização de alguém,sou nova aqui e nunca morei em condomínio. Preciso de uma autorização e não obtive resposta do síndico responsável do dia de hoje. Peço desculpas pelo ocorrido,mas estou muito indignada por não ter assistência que preciso pagando um condomínio tão caro como o que pago aqui.','resolved','Bom dia! A saída é de segunda a sexta de 8 às 17h e sábado de 8 às 12h. A situação foi resolvida? Pois fazer uma autorização para você e pega aqui na administração e assina. 
Até, Francielle Baptista.','2025-10-06 11:24:48.066-03'),
  (35,42,'2025-10-09 18:54:20.291638-03','203','42','Portaria eletronica','Hoje, entre 18:45 a 18:49 fiquei presa na portaria eletronica pois segundo os porteiros a placa de meu carro não foi lida, estava chovendo e o porteiro queria que eu saísse do carro para fazer a identificação facial, me recusei e eles abriram o portão. Mas o constrangimento estava causado, uma fila gigantesca atrás de mim reclamando.
Não e a primeira vez que isso acontece, antes de mim entrou um carro de aplicativo em que os porteiros fizeram a abertura manual da cancela, tanto que pode-se comprovar na câmera que o morador desde para fazer a identificação facial e a cancela já se encontrava aberta.

É indignante estar com todos os cadastros realizados, condomínio em dia e ser tratada de forma grosseira pelos porteiros exigindo que faça uma ação que não é devida.

Repetirei a negativa de descer do carro para fazer a identificação, cave ao condomínio consultar a placa cadastrada ou tomar outra atitude.

Repito, não é a primeira ou segunda vez que isso acontece. Uma vez fui a ADM na exata mesma hora e o funcionário puxou as câmeras e viu toda dinâmica, informou-me que foi registrado o erro da portaria e que este seria corrigido, fato que não ocorreu.

Peço medidas','pending','Bom dia! Iremos verificar a câmera, em caso de chuva acontece da leitura falhar  mesmo. Quando for possível você vim na administração, para verificarmos a placa, ela pode estar com alguma rasura, ou falha, aí precisamos faremos alguma alguma troca se necessário. Att, Francielle Baptista.','2025-10-10 09:46:25.006-03'),
  (36,42,'2025-11-05 22:12:28.009247-03','201','17','Som alto','Já passam das 22h, o som está alto ainda no salão de festa. Liguei para a portaria, pedi para reduzir o volume do som mas não foi baixado ainda. Minha casa está toda fechada para ver se melhora o som, mas nem assim. Um calor absurdo dentro de casa e um som alto e de gosto duvidoso.','pending','Bom dia! Vou passar a situação para o síndico, mas já conversamos com o morador devido a outras questões causadas nesta festa. Att, Francielle Baptista.','2025-11-07 09:23:30.566-03'),
  (37,42,'2025-11-10 07:09:35.151124-03','301','87','Limpeza - área do lixo - 87 - 301','Bom dia. Hoje, ao recolher meu lixo, encontrei o local com vidros, papelão e pedaços de madeira. Solicito, por gentileza, a limpeza imediata para evitar acidentes com terceiros.
Já enviei uma filmagem via WhatsApp para o número +55 22 99227-5387, às 7h04.
Obrigado.','pending','Bom dia, Moacyr! Já irei solicitar a limpeza e verificar o vídeo. Att, Francielle Baptista.','2025-11-10 09:19:53.136-03'),
  (38,42,'2025-11-14 21:16:13.448615-03','204','46','Roubo','Botamos uma Guirlanda na nossa porta, no bloco 46 e foi roubada','pending','Resolvido!','2025-11-17 17:50:28.945-03'),
  (39,42,'2025-12-05 21:54:07.590884-03','201','17','Música alta','Música extremamente alta, já pedi para baixar mas não baixaram. Parece até que colocou mais alto. Quando liguei, o segurança disse q ainda não eram 22h, mas não é direito do vizinho ouvir som alto no nível de incomodar antes das 22h. Achei bem desrespeitoso da parte do dono da festa.','pending','Bom dia! O som baixou às 22h? O vigia foi ao salão de festa?','2025-12-06 08:25:29.219-03'),
  (41,42,'2025-12-12 08:36:57.240334-03','301','87','Reclamação','Bom dia. Hoje, pela manhã, encontrei a área atrás do meu bloco 87 com lixo e pequena sujeira no chão, motivo pelo qual encaminho o registro no WhatsApp do condomínio para as providências cabíveis. Obrigado.','pending','Bom dia! Vou solicitar a limpeza, só não te garanto que será limpo hoje, por conta do funcionamento ser reduzido no sábado. Att, Francielle Baptista.','2025-12-13 10:38:56.331-03'),
  (42,42,'2025-12-20 10:45:52.603415-03','301','87','Limpeza','Bom dia. Hoje, pela manhã, encontrei a área atrás do meu bloco 87 com lixo, motivo pelo qual encaminho o registro no WhatsApp do condomínio para as providências cabíveis. Obrigado.','pending','Bom dia! Vou solicitar a limpeza.','2025-12-22 08:48:27.142-03'),
  (43,42,'2025-12-23 18:56:40.593286-03','103','32','Barulho de reparos fora de hora','O apartamento acima do meu com batidas fortes de martelo ou marretas após as 18:00hs.','pending','Bom dia! O barulho cessou, ou continua?','2025-12-24 11:01:23.348-03'),
  (45,42,'2026-01-03 09:51:36.077693-03','103','90','Proibição de visita ...','Proibida a entrada de Camila leite Brito em qualquer situação salvo mediante a autorização prévia de Vinícius ou Priscila moradores....','pending',NULL,NULL),
  (46,42,'2026-01-17 18:54:59.060879-03','303','32','Sem luz na escada bloco 32','Sem luz escada escura','pending',NULL,NULL),
  (48,42,'2026-02-10 19:34:51.911276-03','103','86','MANUTENÇÃO','BLOCO 86 NO ROL DE ENTRADA NA PARTE 

EXTEŔNA SE ENCONTA COM A LÂMPADA 

QUEIMADA','pending','Bom dia! Já foi trocado. Att, Francielle Baptista.','2026-02-13 10:15:07.175-03'),
  (49,42,'2026-03-03 21:19:38.297868-03','203','80','Lâmpada queimada','A Lâmpada do segundo andar do bloco 80, está queimada.','pending','Bom dia! Vou solicitar a troca. Att, Francielle Baptista.','2026-03-04 09:24:52.049-03');

  -- 2. Insert into ocorrencias, matching users by bloco+apto in perfil
  FOR rec IN SELECT * FROM tmp_ocorrencias_import ORDER BY old_id LOOP
    -- Determine new condominio UUID
    CASE rec.old_condo_id
      WHEN 41 THEN v_condo_id := v_condo_montserrat;
      WHEN 42 THEN v_condo_id := v_condo_recanto;
      ELSE v_condo_id := NULL;
    END CASE;

    IF v_condo_id IS NULL THEN
      v_skipped := v_skipped + 1;
      CONTINUE;
    END IF;

    -- Find user by bloco+apto
    SELECT id INTO v_user_id
      FROM public.perfil
      WHERE condominio_id = v_condo_id
        AND UPPER(TRIM(bloco_txt)) = UPPER(TRIM(rec.bloco))
        AND TRIM(apto_txt) = TRIM(rec.apto)
      ORDER BY created_at DESC
      LIMIT 1;

    IF v_user_id IS NULL THEN
      v_skipped := v_skipped + 1;
      RAISE NOTICE 'SKIP old_id=% - no perfil for bloco=% apto=% (condo=%)', rec.old_id, rec.bloco, rec.apto, rec.old_condo_id;
      CONTINUE;
    END IF;

    -- Insert occurrence
    INSERT INTO public.ocorrencias (
      resident_id, condominio_id, assunto, description,
      status, admin_response, admin_response_at,
      created_at, updated_at
    ) VALUES (
      v_user_id, v_condo_id, rec.assunto, rec.description,
      rec.status, rec.admin_response, rec.admin_response_at,
      rec.created_at, COALESCE(rec.admin_response_at, rec.created_at)
    );

    v_count := v_count + 1;
  END LOOP;

  DROP TABLE tmp_ocorrencias_import;


  RAISE NOTICE '=== OCORRENCIAS IMPORT COMPLETE: % imported, % skipped ===', v_count, v_skipped;
END $$;
